version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 18
      - echo Installing app dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
      - echo Run tests..
      - npm test
  post_build:
    commands:
      - npm run docs:build
  cache:
    paths:
      - "node_modules/**/*"
